spring.application.name=ReportGeneratorBackend
# ===============================================================
# ??????
# ===============================================================

# ???????????????1MB??????50MB?
spring.servlet.multipart.max-file-size=50MB

# ???? multipart ???????????10MB??????50MB?
# ?????????? max-file-size?
spring.servlet.multipart.max-request-size=50MB
